#!/bin/bash

readonly GOPATH="${GOPATH%%:*}"

main() {
  check_fmt
  check_lint
}

check_fmt() {
  eval "set -e"
  for file in $(git ls-files '*.go') ; do
    gofmt -s $file | diff -u $file -
  done
  eval "set +e"
}

check_lint() {
  for file in $(git ls-files '*.go') ; do
    if [[ ! "$(${GOPATH}/bin/golint $file)" =~ ^[[:blank:]]*$ ]] ; then
      _lint_verbose && exit 1
    fi
  done
}

_lint_verbose() {
  for file in $(git ls-files '*.go') ; do $GOPATH/bin/golint $file ; done
}

main "$@"
